version: '3.5'

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 80:80
        volumes:
            - ./:/var/www/html/

    mysql:
        container_name: mysql
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: scandiweb

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8081:80
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
